from django.urls import path
from .views import (
    dashboard,
    class_section_list, class_section_edit, class_section_delete, class_section_create, class_section_detail,
    student_list, student_edit, student_delete, student_create,
    teacher_list, teacher_edit, teacher_delete, teacher_create,
    subject_list, subject_edit, subject_delete, subject_create,
    exam_list, exam_edit, exam_delete, exam_create,
    mark_report,
    excel_upload,
    id_cards,
    AdminLoginView,
    custom_logout_view,
    settings,
    manage_classes, manage_divisions,
    section_marks_entry,
    student_mark_entry,
)

urlpatterns = [
    path('admin/login/', AdminLoginView.as_view(), name='admin_login'),
    path('admin/logout/', custom_logout_view, name='admin_logout'),
    path('', dashboard, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('class-sections/', class_section_list, name='class_section_list'),
    path('class-sections/add/', class_section_create, name='class_section_create'),
    path('class-sections/<int:pk>/', class_section_detail, name='class_section_detail'),
    path('class-sections/<int:pk>/edit/', class_section_edit, name='class_section_edit'),
    path('class-sections/<int:pk>/delete/', class_section_delete, name='class_section_delete'),
    path('students/', student_list, name='student_list'),
    path('students/add/', student_create, name='student_create'),
    path('students/<int:pk>/edit/', student_edit, name='student_edit'),
    path('students/<int:pk>/delete/', student_delete, name='student_delete'),
    path('teachers/', teacher_list, name='teacher_list'),
    path('teachers/add/', teacher_create, name='teacher_create'),
    path('teachers/<int:pk>/edit/', teacher_edit, name='teacher_edit'),
    path('teachers/<int:pk>/delete/', teacher_delete, name='teacher_delete'),
    path('subjects/', subject_list, name='subject_list'),
    path('subjects/add/', subject_create, name='subject_create'),
    path('subjects/<int:pk>/edit/', subject_edit, name='subject_edit'),
    path('subjects/<int:pk>/delete/', subject_delete, name='subject_delete'),
    path('exams/', exam_list, name='exam_list'),
    path('exams/add/', exam_create, name='exam_create'),
    path('exams/<int:pk>/edit/', exam_edit, name='exam_edit'),
    path('exams/<int:pk>/delete/', exam_delete, name='exam_delete'),
    path('reports/marks/', mark_report, name='mark_report'),
    path('upload/excel/', excel_upload, name='excel_upload'),
    path('id-cards/', id_cards, name='id_cards'),
    path('settings/', settings, name='settings'),
    path('manage/classes/', manage_classes, name='manage_classes'),
    path('manage/divisions/', manage_divisions, name='manage_divisions'),
    # Add aliases for subject/exam CRUD for template compatibility
    path('subjects/add/', subject_create, name='add-subject'),
    path('subjects/<int:pk>/edit/', subject_edit, name='edit-subject'),
    path('subjects/<int:pk>/delete/', subject_delete, name='delete-subject'),
    path('exams/add/', exam_create, name='add-exam'),
    path('exams/<int:pk>/edit/', exam_edit, name='edit-exam'),
    path('exams/<int:pk>/delete/', exam_delete, name='delete-exam'),
    path('sections/<int:section_id>/marks-entry/', section_marks_entry, name='section_marks_entry'),
    path('students/<int:student_id>/mark-entry/', student_mark_entry, name='student_mark_entry'),
]
