# Generated by Django 5.2.2 on 2025-06-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_number', 'class_division')},
        ),
    ]
